# frozen_string_literal: true

require "test_helper"
require "fileutils"
require "rails/generators"
require "tmpdir"
require "generators/quality_gate/install/install_generator"

module QualityGate
  # rubocop:disable Metrics/AbcSize
  class InstallGeneratorTest < Minitest::Test
    STRONG_MIGRATIONS_PROVENANCE = "# Generated by Quality Gate.\n"
    STRONG_MIGRATIONS_HEADER = <<~RUBY
      # frozen_string_literal: true

      require 'strong_migrations'

      # Generated by Quality Gate.
    RUBY
    INVALID_STRONG_MIGRATIONS_BASELINES = [
      "_baseline",
      "_1",
      "_20_260_829_010_101",
      "20_260_829_010_101_",
      "20__260_829_010_101",
      "20_260_829_010_101 + 1"
    ].freeze
    MANAGED_FILES = %w[
      .quality_gate.yml
      .rubocop.yml
      config/initializers/bullet.rb
      config/initializers/strong_migrations.rb
      test/test_helper.rb
    ].freeze
    AGENT_FILES = %w[
      .claude/hooks/quality_gate_fast.rb
      .claude/hooks/quality_gate_verify_stop.rb
      .claude/settings.json
      CLAUDE.md
      AGENTS.md
    ].freeze

    def test_exposes_the_managed_paths_and_coverage_markers
      assert InstallGenerator.const_defined?(:FILES, false)
      assert_equal MANAGED_FILES + AGENT_FILES, InstallGenerator::FILES
      assert_predicate InstallGenerator::FILES, :frozen?
      assert_equal "# quality_gate coverage — start", InstallGenerator::MARKER_START
      assert_predicate InstallGenerator::MARKER_START, :frozen?
      assert_equal "# quality_gate coverage — end", InstallGenerator::MARKER_END
      assert_predicate InstallGenerator::MARKER_END, :frozen?
    end

    def test_clean_host_receives_all_five_artifacts_and_a_written_summary
      with_host do |host|
        original_helper = File.binread(File.join(host, "test/test_helper.rb"))

        stdout, stderr = run_generator(host)

        assert_empty stderr
        MANAGED_FILES.each { assert_path_exists File.join(host, _1) }
        settings = Config.load(dir: host)
        assert_equal %w[bin/rails test], settings.fetch(:commands).dig(:verify, :test_suite)
        assert_equal expected_template("rubocop.yml.tt"), read(host, ".rubocop.yml")
        assert_equal expected_template("bullet.rb.tt"), read(host, "config/initializers/bullet.rb")
        assert_equal "#{STRONG_MIGRATIONS_HEADER}StrongMigrations.start_after = 20_260_829_010_101\n",
                     read(host, "config/initializers/strong_migrations.rb")
        assert_equal expected_covered_helper(original_helper), read(host, "test/test_helper.rb")
        refute_path_exists File.join(host, ".github/workflows/quality_gate.yml")
        MANAGED_FILES.each { assert_match(/^  - #{Regexp.escape(_1)}$/, stdout) }
        assert_match(/^Written:$/, stdout)
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_ci_workflow_is_opt_in_and_rerunning_without_ci_preserves_it
      with_host do |host|
        stdout, stderr = run_generator(host, "--ci")
        workflow_path = File.join(host, ".github/workflows/quality_gate.yml")

        assert_empty stderr
        assert_path_exists workflow_path
        content = read(host, ".github/workflows/quality_gate.yml")
        assert_includes content, "push:"
        assert_includes content, "pull_request:"
        assert_includes content, "contents: read"
        assert_includes content, "uses: actions/checkout@v7"
        assert_includes content, "uses: ruby/setup-ruby@v1"
        assert_includes content, "ruby-version: \"#{RUBY_VERSION}\""
        assert_includes content, "fetch-depth: 0"
        assert_includes content, "persist-credentials: false"
        %w[fast verify audit].each { assert_includes content, "run: bundle exec quality_gate #{_1}" }
        assert_includes summary_entries(stdout, "Written"), ".github/workflows/quality_gate.yml"

        rerun_stdout, rerun_ci_stderr = run_generator(host, "--ci")

        assert_empty rerun_ci_stderr
        assert_equal content, File.read(workflow_path)
        assert_includes summary_entries(rerun_stdout, "Unchanged"), ".github/workflows/quality_gate.yml"

        _stdout, rerun_stderr = run_generator(host)

        assert_empty rerun_stderr
        assert_equal content, File.read(workflow_path)
      end
    end

    def test_ci_preview_does_not_write_a_workflow
      with_host do |host|
        _stdout, stderr = run_generator(host, "--ci", "--pretend")

        assert_empty stderr
        refute_path_exists File.join(host, ".github/workflows/quality_gate.yml")
      end
    end

    def test_ci_install_preserves_custom_and_unrelated_workflows
      with_host do |host|
        workflow_path = File.join(host, ".github/workflows/quality_gate.yml")
        other_path = File.join(host, ".github/workflows/release.yml")
        FileUtils.mkdir_p(File.dirname(workflow_path))
        File.write(workflow_path, "name: Host-owned workflow\n")
        File.write(other_path, "name: Release\n")

        stdout, stderr = run_generator(host, "--ci")

        assert_empty stderr
        assert_equal "name: Host-owned workflow\n", File.read(workflow_path)
        assert_equal "name: Release\n", File.read(other_path)
        assert_includes summary_entries(stdout, "Needs a person"), ".github/workflows/quality_gate.yml"
      end
    end

    def test_default_install_skips_agent_integration_and_reports_the_opt_in_hint
      with_host do |host|
        stdout, stderr = run_generator(host)

        assert_empty stderr
        %w[
          .claude/hooks/quality_gate_fast.rb
          .claude/hooks/quality_gate_verify_stop.rb
          .claude/settings.json
          CLAUDE.md
          AGENTS.md
        ].each { refute_path_exists File.join(host, _1) }
        assert_includes summary_entries(stdout, "Skipped"),
                        "agent integration (pass --agents to install Claude hooks and contracts)"
      end
    end

    def test_rspec_helper_and_custom_command_are_covered_and_rendered_as_yaml_argv
      with_host(test_helper: false) do |host|
        helper = File.join(host, "spec/support/custom_rails_helper.rb")
        FileUtils.mkdir_p(File.dirname(helper))
        File.binwrite(helper, "#!/usr/bin/env ruby\n# host helper\nrequire_relative \"../../config/environment\"\n")
        command = "bundle exec rspec --format 'doc' --tag feature:test"

        stdout, stderr = run_generator(
          host,
          "--test-helper", "spec/support/custom_rails_helper.rb",
          "--test-command", command
        )

        assert_empty stderr
        settings = Config.load(dir: host)
        assert_equal %w[bundle exec rspec --format doc --tag feature:test],
                     settings.fetch(:commands).dig(:verify, :test_suite)
        assert_equal Config.defaults.fetch(:adapters), settings.fetch(:adapters)
        covered = read(host, "spec/support/custom_rails_helper.rb")
        assert_operator covered.index(InstallGenerator::MARKER_START.b), :<, covered.index("require_relative".b)
        assert_operator covered.index("SimpleCov.start".b), :<, covered.index("require_relative".b)
        assert_includes covered, "add_filter '/test/'"
        assert_includes covered, "add_filter '/spec/'"
        assert_includes summary_entries(stdout, "Written"), "spec/support/custom_rails_helper.rb"

        before = tree_snapshot(host)
        second_stdout, second_stderr = run_generator(
          host,
          "--test-helper", "spec/support/custom_rails_helper.rb",
          "--test-command", command
        )

        assert_empty second_stderr
        assert_equal before, tree_snapshot(host)
        assert_includes summary_entries(second_stdout, "Unchanged"), "spec/support/custom_rails_helper.rb"
      end
    end

    def test_profile_errors_are_preflighted_before_any_generator_write
      with_host do |host|
        spec_helper = File.join(host, "spec/rails_helper.rb")
        FileUtils.mkdir_p(File.dirname(spec_helper))
        File.write(spec_helper, "# RSpec helper\n")
        before = tree_snapshot(host)

        [
          ["--test-framework", "cucumber"],
          ["--test-helper", "../outside.rb"],
          ["--test-framework", "minitest", "--test-command", "  "],
          []
        ].each do |arguments|
          exception = nil
          begin
            run_generator(host, *arguments)
          rescue StandardError => e
            exception = e
          end

          assert_instance_of ArgumentError, exception
          assert_equal before, tree_snapshot(host), arguments.inspect
        end
      end
    end

    def test_ambiguous_test_and_spec_helpers_fail_before_writing
      with_host do |host|
        spec_helper = File.join(host, "spec/rails_helper.rb")
        FileUtils.mkdir_p(File.dirname(spec_helper))
        File.write(spec_helper, "# RSpec helper\n")
        before = tree_snapshot(host)

        exception = assert_raises(ArgumentError) { run_generator(host) }

        assert_includes exception.message, "test-framework"
        assert_equal before, tree_snapshot(host)
      end
    end

    def test_rspec_helper_symlink_components_fail_before_any_generator_write
      with_host(test_helper: false) do |host, parent|
        external_directory = File.join(parent, "outside-spec")
        FileUtils.mkdir_p(external_directory)
        external = File.join(external_directory, "rails_helper.rb")
        File.write(external, "# external helper\n")
        spec_directory = File.join(host, "spec")
        FileUtils.mkdir_p(spec_directory)
        cases = {
          "symlinked helper directory" => -> { File.symlink(external_directory, spec_directory) },
          "symlinked helper file" => lambda {
            FileUtils.mkdir_p(spec_directory)
            File.symlink(external, File.join(spec_directory, "rails_helper.rb"))
          }
        }

        cases.each do |description, setup|
          FileUtils.rm_rf(spec_directory)
          setup.call
          before_host = tree_snapshot(host)
          before_outside = outside_snapshot(parent, host)
          exception = nil

          begin
            run_generator(host, "--test-framework", "rspec")
          rescue StandardError => e
            exception = e
          end

          assert_instance_of ArgumentError, exception, description
          assert_equal before_host, tree_snapshot(host), description
          assert_equal before_outside, outside_snapshot(parent, host), description
        end
      end
    end

    def test_rspec_preview_and_customized_settings_preserve_the_host_tree
      with_host(test_helper: false) do |host|
        helper = File.join(host, "spec/rails_helper.rb")
        FileUtils.mkdir_p(File.dirname(helper))
        File.write(helper, "require_relative '../config/environment'\n")
        before_preview = tree_snapshot(host)

        run_generator(host, "--test-framework", "rspec", "--pretend")

        assert_equal before_preview, tree_snapshot(host)

        custom_settings = "# host-owned settings\nadapters:\n  fast:\n    - rubocop\n"
        File.write(File.join(host, ".quality_gate.yml"), custom_settings)
        before_custom = File.binread(File.join(host, ".quality_gate.yml"))

        stdout, stderr = run_generator(host, "--test-framework", "rspec")

        assert_empty stderr
        assert_equal before_custom, File.binread(File.join(host, ".quality_gate.yml"))
        assert_includes summary_entries(stdout, "Needs a person"), ".quality_gate.yml"
        assert_includes summary_entries(stdout, "Written"), "spec/rails_helper.rb"
      end
    end

    def test_default_install_preserves_existing_agent_files
      with_host do |host|
        agent_files = {
          ".claude/hooks/quality_gate_fast.rb" => "#!/usr/bin/env ruby\n# custom fast hook\n",
          ".claude/hooks/quality_gate_verify_stop.rb" => "#!/usr/bin/env ruby\n# custom stop hook\n",
          ".claude/settings.json" => "{\"hooks\": {}}\n",
          "CLAUDE.md" => "# Claude notes\n",
          "AGENTS.md" => "# Agent notes\n"
        }
        agent_files.each do |relative_path, content|
          path = File.join(host, relative_path)
          FileUtils.mkdir_p(File.dirname(path))
          File.binwrite(path, content)
        end
        before = agent_files.to_h { |relative_path, _content| [relative_path, read(host, relative_path)] }

        stdout, stderr = run_generator(host)

        assert_empty stderr
        after = agent_files.to_h { |relative_path, _content| [relative_path, read(host, relative_path)] }
        assert_equal before, after
        assert_includes summary_entries(stdout, "Skipped"),
                        "agent integration (pass --agents to install Claude hooks and contracts)"
      end
    end

    def test_second_run_preserves_contents_and_timestamps_and_reports_everything_unchanged
      with_host do |host|
        run_generator(host)
        MANAGED_FILES.each_with_index do |relative_path, index|
          timestamp = Time.at(1_700_000_000 + index)
          File.utime(timestamp, timestamp, File.join(host, relative_path))
        end
        before = managed_snapshot(host)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal before, managed_snapshot(host)
        assert_equal 1, read(host, "test/test_helper.rb").scan(InstallGenerator::MARKER_START.b).length
        assert_empty summary_entries(stdout, "Written")
        assert_equal MANAGED_FILES, summary_entries(stdout, "Unchanged")
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_strong_migrations_generated_baseline_stays_unchanged_after_newer_migrations_appear
      with_host do |host|
        run_generator(host)
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        original = File.binread(initializer_path)
        timestamp = Time.at(1_700_000_050)
        File.utime(timestamp, timestamp, initializer_path)
        File.binwrite(File.join(host, "db/migrate/20270829010101_add_status.rb"), "# fixture\n")

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal original, File.binread(initializer_path)
        assert_equal timestamp, File.mtime(initializer_path)
        assert_includes summary_entries(stdout, "Unchanged"), "config/initializers/strong_migrations.rb"
        refute_includes summary_entries(stdout, "Needs a person"), "config/initializers/strong_migrations.rb"
        refute_includes stdout, "StrongMigrations.start_after = 20_270_829_010_101"
      end
    end

    def test_customized_marked_strong_migrations_guidance_preserves_its_historical_baseline
      with_host do |host|
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        FileUtils.mkdir_p(File.dirname(initializer_path))
        custom = <<~RUBY
          #{STRONG_MIGRATIONS_PROVENANCE.chomp}
          # Developer-owned settings.
          StrongMigrations.start_after = 20240101000000
          StrongMigrations.lock_timeout = 5.seconds
        RUBY
        File.binwrite(initializer_path, custom)
        timestamp = Time.at(1_700_000_075)
        File.utime(timestamp, timestamp, initializer_path)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal custom, File.binread(initializer_path)
        assert_equal timestamp, File.mtime(initializer_path)
        expected = "#{STRONG_MIGRATIONS_HEADER}StrongMigrations.start_after = 20_240_101_000_000\n"
        assert_includes stdout, "Use these lines manually for config/initializers/strong_migrations.rb:\n#{expected}"
        refute_includes stdout, "StrongMigrations.start_after = 20_260_829_010_101"
        assert_includes summary_entries(stdout, "Needs a person"),
                        "config/initializers/strong_migrations.rb"
      end
    end

    def test_customized_unmarked_strong_migrations_guidance_preserves_its_existing_baseline
      with_host do |host|
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        FileUtils.mkdir_p(File.dirname(initializer_path))
        custom = <<~RUBY
          # Developer-owned settings.
          StrongMigrations.start_after = 20240202000000 # Historical baseline.
          StrongMigrations.lock_timeout = 5.seconds
        RUBY
        File.binwrite(initializer_path, custom)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal custom, File.binread(initializer_path)
        expected = "#{STRONG_MIGRATIONS_HEADER}StrongMigrations.start_after = 20_240_202_000_000\n"
        assert_includes stdout, "Use these lines manually for config/initializers/strong_migrations.rb:\n#{expected}"
        refute_includes stdout, "StrongMigrations.start_after = 20_260_829_010_101"
        assert_includes summary_entries(stdout, "Needs a person"),
                        "config/initializers/strong_migrations.rb"
      end
    end

    def test_unmarked_one_line_strong_migrations_baseline_is_developer_owned
      with_host do |host|
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        FileUtils.mkdir_p(File.dirname(initializer_path))
        developer_content = "StrongMigrations.start_after = 20240303000000\n"
        File.binwrite(initializer_path, developer_content)
        timestamp = Time.at(1_700_000_080)
        File.utime(timestamp, timestamp, initializer_path)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal [developer_content, timestamp], [File.binread(initializer_path), File.mtime(initializer_path)]
        expected = "#{STRONG_MIGRATIONS_HEADER}StrongMigrations.start_after = 20_240_303_000_000\n"
        assert_includes stdout, "Use these lines manually for config/initializers/strong_migrations.rb:\n#{expected}"
        assert_includes summary_entries(stdout, "Needs a person"),
                        "config/initializers/strong_migrations.rb"
        refute_includes summary_entries(stdout, "Unchanged"),
                        "config/initializers/strong_migrations.rb"
      end
    end

    def test_invalid_strong_migrations_baseline_expressions_remain_developer_owned
      INVALID_STRONG_MIGRATIONS_BASELINES.each_with_index do |expression, index|
        with_host do |host|
          initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
          FileUtils.mkdir_p(File.dirname(initializer_path))
          content = "# Developer-owned settings.\nStrongMigrations.start_after = #{expression}\n"
          File.binwrite(initializer_path, content)
          timestamp = Time.at(1_700_000_085 + index)
          File.utime(timestamp, timestamp, initializer_path)
          exception = nil
          stdout, stderr = begin
            run_generator(host)
          rescue StandardError => e
            exception = e
            ["", ""]
          end

          assert_nil exception, "#{expression.inspect} raised #{exception&.class}: #{exception&.message}"
          assert_empty stderr
          assert_equal [content, timestamp], [File.binread(initializer_path), File.mtime(initializer_path)]
          assert_includes summary_entries(stdout, "Needs a person"),
                          "config/initializers/strong_migrations.rb"
          assert_includes stdout, "StrongMigrations.start_after = 20_260_829_010_101"
        end
      end
    end

    def test_generated_no_migration_guidance_stays_stable_when_a_migration_appears
      with_host do |host|
        migration = File.join(host, "db/migrate/20260829010101_create_accounts.rb")
        File.delete(migration)
        run_generator(host)
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        original = File.binread(initializer_path)
        timestamp = Time.at(1_700_000_090)
        File.utime(timestamp, timestamp, initializer_path)
        File.binwrite(migration, "# fixture\n")

        stdout, stderr = run_generator(host)

        assert_empty stderr
        expected = <<~RUBY
          #{STRONG_MIGRATIONS_HEADER.chomp}
          # Set StrongMigrations.start_after after the first migration exists.
        RUBY
        assert_equal expected, original
        assert_equal [original, timestamp], [File.binread(initializer_path), File.mtime(initializer_path)]
        assert_includes summary_entries(stdout, "Unchanged"), "config/initializers/strong_migrations.rb"
        refute_includes stdout, "StrongMigrations.start_after = 20_260_829_010_101"
      end
    end

    def test_legacy_generated_no_migration_headers_do_not_adopt_a_newer_baseline
      legacy_headers = [
        STRONG_MIGRATIONS_PROVENANCE,
        "require \"strong_migrations\"\n\n#{STRONG_MIGRATIONS_PROVENANCE}"
      ]

      legacy_headers.each do |header|
        with_host do |host|
          initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
          FileUtils.mkdir_p(File.dirname(initializer_path))
          content = "#{header}# Set StrongMigrations.start_after after the first migration exists.\n"
          File.binwrite(initializer_path, content)
          timestamp = Time.at(1_700_000_095)
          File.utime(timestamp, timestamp, initializer_path)

          stdout, stderr = run_generator(host)

          assert_empty stderr
          assert_equal [content, timestamp], [File.binread(initializer_path), File.mtime(initializer_path)]
          assert_includes summary_entries(stdout, "Needs a person"),
                          "config/initializers/strong_migrations.rb"
          refute_includes stdout, "StrongMigrations.start_after = 20_260_829_010_101"
        end
      end
    end

    def test_incidental_early_provenance_comment_remains_developer_owned
      with_host do |host|
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        FileUtils.mkdir_p(File.dirname(initializer_path))
        content = <<~RUBY
          # frozen_string_literal: true
          # Developer-owned configuration.
          #{STRONG_MIGRATIONS_PROVENANCE.chomp}
          # This marker is documentation, not a generated header.
        RUBY
        File.binwrite(initializer_path, content)
        timestamp = Time.at(1_700_000_096)
        File.utime(timestamp, timestamp, initializer_path)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal [content, timestamp], [File.binread(initializer_path), File.mtime(initializer_path)]
        assert_includes summary_entries(stdout, "Needs a person"), "config/initializers/strong_migrations.rb"
        refute_includes summary_entries(stdout, "Unchanged"), "config/initializers/strong_migrations.rb"
        assert_includes stdout, "StrongMigrations.start_after = 20_260_829_010_101"
      end
    end

    def test_unmarked_stock_no_migration_comment_is_not_inferred_as_generated
      with_host do |host|
        initializer_path = File.join(host, "config/initializers/strong_migrations.rb")
        FileUtils.mkdir_p(File.dirname(initializer_path))
        developer_content = "# Set StrongMigrations.start_after after the first migration exists.\n"
        File.binwrite(initializer_path, developer_content)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal developer_content, File.binread(initializer_path)
        expected = "#{STRONG_MIGRATIONS_HEADER}StrongMigrations.start_after = 20_260_829_010_101\n"
        assert_includes stdout, "Use these lines manually for config/initializers/strong_migrations.rb:\n#{expected}"
        assert_includes summary_entries(stdout, "Needs a person"),
                        "config/initializers/strong_migrations.rb"
        refute_includes summary_entries(stdout, "Unchanged"),
                        "config/initializers/strong_migrations.rb"
      end
    end

    def test_divergent_rules_are_untouched_and_printed_for_manual_action_while_other_files_install
      with_host do |host|
        rules_path = File.join(host, ".rubocop.yml")
        existing_rules = "AllCops:\n  NewCops: enable\n".b
        File.binwrite(rules_path, existing_rules)
        timestamp = Time.at(1_700_000_100)
        File.utime(timestamp, timestamp, rules_path)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal existing_rules, File.binread(rules_path)
        assert_equal timestamp, File.mtime(rules_path)
        assert_includes stdout, "Use these lines manually for .rubocop.yml:\n#{expected_template("rubocop.yml.tt")}"
        assert_equal [".rubocop.yml"], summary_entries(stdout, "Needs a person")
        assert_equal MANAGED_FILES - [".rubocop.yml"], summary_entries(stdout, "Written")
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_skip_options_leave_initializers_and_test_helper_unmanaged
      with_host do |host|
        helper_path = File.join(host, "test/test_helper.rb")
        original_helper = File.binread(helper_path)
        timestamp = Time.at(1_700_000_200)
        File.utime(timestamp, timestamp, helper_path)

        stdout, stderr = run_generator(host, "--skip-initializers", "--skip-coverage")

        assert_empty stderr
        assert_path_exists File.join(host, ".quality_gate.yml")
        assert_path_exists File.join(host, ".rubocop.yml")
        refute_path_exists File.join(host, "config/initializers/bullet.rb")
        refute_path_exists File.join(host, "config/initializers/strong_migrations.rb")
        assert_equal original_helper, File.binread(helper_path)
        assert_equal timestamp, File.mtime(helper_path)
        assert_equal MANAGED_FILES - %w[
          config/initializers/bullet.rb
          config/initializers/strong_migrations.rb
          test/test_helper.rb
        ], summary_entries(stdout, "Written")
        %w[config/initializers/bullet.rb config/initializers/strong_migrations.rb test/test_helper.rb].each do |path|
          refute_includes stdout, path
        end
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_pretend_preserves_the_complete_host_tree_and_reports_pending_writes_as_skipped
      with_host do |host|
        before = tree_snapshot(host)

        stdout, stderr = run_generator(host, "--pretend")

        assert_empty stderr
        assert_equal before, tree_snapshot(host)
        assert_empty summary_entries(stdout, "Written")
        assert_equal [*MANAGED_FILES.map { "#{_1} (pretend)" },
                      "agent integration (pass --agents to install Claude hooks and contracts)"],
                     summary_entries(stdout, "Skipped")
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_revoke_is_a_read_only_unsupported_operation_with_manual_removal_direction
      with_host do |host|
        run_generator(host)
        helper_path = File.join(host, "test/test_helper.rb")
        File.binwrite(helper_path, "require \"host\"\n")
        before = tree_snapshot(host)

        stdout, stderr = run_generator(host, behavior: :revoke)

        assert_empty stderr
        assert_equal before, tree_snapshot(host)
        assert_includes stdout, "Automatic removal is not supported."
        assert_match(/README.*manual removal/i, stdout)
        refute_includes stdout, "Written:"
        refute_includes stdout, "Next: bundle exec quality_gate fast"
      end
    end

    def test_missing_test_helper_warns_and_skips_coverage_while_four_files_install
      with_host(test_helper: false) do |host|
        exception = nil
        stdout, stderr = begin
          run_generator(host)
        rescue StandardError => e
          exception = e
          ["", ""]
        end

        assert_nil exception
        assert_empty stderr
        assert_equal MANAGED_FILES - ["test/test_helper.rb"], summary_entries(stdout, "Written")
        assert_equal [
          "test/test_helper.rb (missing; Minitest coverage wiring skipped)",
          "agent integration (pass --agents to install Claude hooks and contracts)"
        ], summary_entries(stdout, "Skipped")
        warning = %r{Warning: Minitest coverage wiring skipped; test/test_helper\.rb is missing\.}
        assert_equal 1, stdout.scan(warning).length
        refute_path_exists File.join(host, "test/test_helper.rb")
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_existing_coverage_marker_leaves_the_helper_untouched
      with_host do |host|
        helper_path = File.join(host, "test/test_helper.rb")
        existing = <<~RUBY.b
          #{InstallGenerator::MARKER_START}
          # developer-managed coverage setup
          #{InstallGenerator::MARKER_END}
          require_relative "../config/environment"
        RUBY
        File.binwrite(helper_path, existing)
        timestamp = Time.at(1_700_000_300)
        File.utime(timestamp, timestamp, helper_path)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal existing, File.binread(helper_path)
        assert_equal timestamp, File.mtime(helper_path)
        assert_equal ["test/test_helper.rb"], summary_entries(stdout, "Unchanged")
        assert_equal 1, File.binread(helper_path).scan(InstallGenerator::MARKER_START.b).length
      end
    end

    def test_coverage_preserves_ruby_prologues_host_newlines_and_surrounding_bytes
      bom = "\xEF\xBB\xBF".b
      lf_prologue = <<~'RUBY'.b
        #!/usr/bin/env ruby

        # Copyright 2026 Example Authors.
        # Ordinary comments remain part of the source header.
        # shareable_constant_value: literal
        # warn_indent: true
        # -*- mode: ruby; coding: UTF-8; frozen_string_literal: true -*-

      RUBY
      crlf_prologue = lf_prologue.gsub("\n".b, "\r\n".b)
      block_comment_prologue = <<~'RUBY'.b
        =begin
        Host test-helper documentation.
        Coverage must remain after this non-executable block.
        =end

      RUBY
      lf_original = [bom, lf_prologue, "require \"host\"\n"].join.b
      lf_expected = [bom, lf_prologue, coverage_block("\n"), "require \"host\"\n"].join.b
      crlf_original = [crlf_prologue, "require \"host\"\r\n"].join.b
      crlf_expected = [crlf_prologue, coverage_block("\r\n"), "require \"host\"\r\n"].join.b
      block_original = block_comment_prologue + "require \"host\"\n".b
      block_expected = block_comment_prologue + coverage_block("\n") + "require \"host\"\n".b
      incomplete_block = "=begin\nHost documentation without a terminator.\nrequire \"host\"\n".b
      cases = {
        "BOM, ordinary comments, and complete directives" => [lf_original, lf_expected],
        "CRLF prologue" => [crlf_original, crlf_expected],
        "leading block comment" => [block_original, block_expected],
        "unterminated block comment" => [incomplete_block, coverage_block("\n") + incomplete_block],
        "empty helper" => ["".b, coverage_block("\n")],
        "no final newline" => ["require \"host\"".b, coverage_block("\n") + "require \"host\"".b]
      }

      cases.each do |name, (original, expected)|
        with_host do |host|
          File.binwrite(File.join(host, "test/test_helper.rb"), original)

          run_generator(host)

          assert_equal expected.b, read(host, "test/test_helper.rb"), name
        end
      end
    end

    def test_coverage_replaces_a_hard_link_without_mutating_the_external_inode
      with_host do |host, parent|
        helper_path = File.join(host, "test/test_helper.rb")
        original = File.binread(helper_path)
        File.chmod(0o740, helper_path)
        external_path = File.join(parent, "external-test-helper.rb")
        File.link(helper_path, external_path)
        original_inode = File.stat(external_path).ino

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal original, File.binread(external_path)
        assert_equal original_inode, File.stat(external_path).ino
        refute_equal original_inode, File.stat(helper_path).ino
        assert_equal 0o740, File.stat(helper_path).mode & 0o777
        assert_equal expected_covered_helper(original), File.binread(helper_path)
        assert_includes summary_entries(stdout, "Written"), "test/test_helper.rb"
      end
    end

    def test_coverage_write_failure_preserves_the_original_and_continues
      with_host do |host|
        helper_path = File.join(host, "test/test_helper.rb")
        test_directory = File.dirname(helper_path)
        original = [File.binread(helper_path), File.stat(helper_path).ino, File.stat(helper_path).mode]
        exception = nil
        File.chmod(0o555, test_directory)
        stdout, stderr = begin
          run_generator(host)
        rescue StandardError => e
          exception = e
          ["", ""]
        ensure
          File.chmod(0o755, test_directory)
        end

        assert_nil exception
        assert_empty stderr
        assert_equal original, [File.binread(helper_path), File.stat(helper_path).ino, File.stat(helper_path).mode]
        assert_equal ["test/test_helper.rb"], summary_entries(stdout, "Needs a person")
        assert_equal MANAGED_FILES - ["test/test_helper.rb"], summary_entries(stdout, "Written")
        assert_empty Dir.glob(File.join(test_directory, ".quality_gate-coverage-*"))
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    def test_symlinked_managed_directory_cannot_write_outside_the_host_root
      with_host do |host, parent|
        outside_config = File.join(parent, "outside-config")
        FileUtils.mkdir_p(File.join(outside_config, "initializers"))
        sentinel = File.join(parent, "sentinel.txt")
        File.binwrite(sentinel, "keep me\n")
        File.symlink(outside_config, File.join(host, "config"))
        before = outside_snapshot(parent, host)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal before, outside_snapshot(parent, host)
        assert_equal "keep me\n", File.binread(sentinel)
        assert_equal ["config/initializers/bullet.rb", "config/initializers/strong_migrations.rb"],
                     summary_entries(stdout, "Needs a person")
        assert_equal MANAGED_FILES - %w[config/initializers/bullet.rb config/initializers/strong_migrations.rb],
                     summary_entries(stdout, "Written")
        refute_path_exists File.join(outside_config, "initializers/bullet.rb")
        refute_path_exists File.join(outside_config, "initializers/strong_migrations.rb")
      end
    end

    def test_directory_at_a_managed_file_path_needs_a_person_and_does_not_stop_installation
      with_host do |host|
        occupied_path = File.join(host, ".quality_gate.yml")
        FileUtils.mkdir(occupied_path)
        File.binwrite(File.join(occupied_path, "sentinel.txt"), "keep me\n")

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_predicate File.lstat(occupied_path), :directory?
        assert_equal "keep me\n", File.binread(File.join(occupied_path, "sentinel.txt"))
        assert_equal [".quality_gate.yml"], summary_entries(stdout, "Needs a person")
        assert_equal MANAGED_FILES - [".quality_gate.yml"], summary_entries(stdout, "Written")
      end
    end

    def test_regular_file_parent_needs_a_person_for_children_and_does_not_stop_installation
      with_host do |host|
        parent_path = File.join(host, "config")
        File.binwrite(parent_path, "developer-owned\n")
        exception = nil
        stdout, stderr = begin
          run_generator(host)
        rescue StandardError => e
          exception = e
          ["", ""]
        end

        assert_nil exception
        assert_empty stderr
        assert_equal "developer-owned\n", File.binread(parent_path)
        assert_equal ["config/initializers/bullet.rb", "config/initializers/strong_migrations.rb"],
                     summary_entries(stdout, "Needs a person")
        assert_equal MANAGED_FILES - %w[config/initializers/bullet.rb config/initializers/strong_migrations.rb],
                     summary_entries(stdout, "Written")
      end
    end

    def test_symlinked_destination_root_cannot_write_into_its_target
      Dir.mktmpdir("quality-gate-symlinked-root") do |parent|
        outside = File.join(parent, "outside")
        FileUtils.mkdir_p(File.join(outside, "test"))
        FileUtils.mkdir_p(File.join(outside, "db/migrate"))
        File.binwrite(File.join(outside, "test/test_helper.rb"), "require \"host\"\n")
        File.binwrite(File.join(outside, "sentinel.txt"), "keep me\n")
        host = File.join(parent, "host")
        File.symlink(outside, host)
        before = outside_snapshot(parent, host)

        stdout, stderr = run_generator(host)

        assert_empty stderr
        assert_equal before, outside_snapshot(parent, host)
        assert_equal MANAGED_FILES, summary_entries(stdout, "Needs a person")
        assert_empty summary_entries(stdout, "Written")
        assert_equal "Next: bundle exec quality_gate fast", stdout.lines.last.chomp
      end
    end

    private

    def with_host(test_helper: true)
      Dir.mktmpdir("quality-gate-install") do |parent|
        host = File.join(parent, "host")
        FileUtils.mkdir_p(File.join(host, "db/migrate"))
        if test_helper
          FileUtils.mkdir_p(File.join(host, "test"))
          File.binwrite(File.join(host, "test/test_helper.rb"), <<~RUBY)
            require_relative "../config/environment"
            require "rails/test_help"
          RUBY
        end
        File.binwrite(File.join(host, "db/migrate/20260829010101_create_accounts.rb"), "# fixture\n")
        yield host, parent
      end
    end

    def run_generator(host, *arguments, behavior: :invoke)
      capture_io { InstallGenerator.start(arguments, destination_root: host, behavior:) }
    end

    def read(host, relative_path)
      File.binread(File.join(host, relative_path))
    end

    def expected_template(name)
      File.binread(File.join(InstallGenerator.source_root, name))
    end

    def expected_covered_helper(original_helper)
      coverage_block("\n") + original_helper
    end

    def coverage_block(newline)
      template = expected_template("simplecov.rb.tt").gsub("\n", newline)
      "#{InstallGenerator::MARKER_START}#{newline}#{template}#{InstallGenerator::MARKER_END}#{newline}".b
    end

    def managed_snapshot(host)
      MANAGED_FILES.to_h do |relative_path|
        path = File.join(host, relative_path)
        [relative_path, [File.binread(path), File.mtime(path)]]
      end
    end

    def summary_entries(stdout, heading)
      lines = stdout.lines.map(&:chomp)
      start = lines.index("#{heading}:")
      return [] unless start

      lines.drop(start + 1).take_while { _1.start_with?("  - ") }.map { _1.delete_prefix("  - ") }
    end

    def outside_snapshot(parent, host)
      Dir.glob(File.join(parent, "**/*"), File::FNM_DOTMATCH).filter_map do |path|
        next unless File.file?(path)
        next if path == host || path.start_with?("#{host}/")

        [path, File.binread(path)]
      end.to_h
    end

    def tree_snapshot(root)
      Dir.glob(File.join(root, "**/*"), File::FNM_DOTMATCH).sort.to_h do |path|
        stat = File.lstat(path)
        relative_path = path.delete_prefix("#{root}/")
        content = File.binread(path) if stat.file?
        [relative_path, [stat.ftype, stat.mode, stat.mtime, content]]
      end
    end
  end
  # rubocop:enable Metrics/AbcSize
end
