# frozen_string_literal: true

require "test_helper"
require "fileutils"
require "json"
require "open3"
require "rails/generators"
require "rbconfig"
require "tmpdir"
require "yaml"
require "generators/quality_gate/install/install_generator"

module QualityGate
  class InstallGeneratorTemplatesTest < Minitest::Test
    QUALITY_GATE_COMMANDS = [
      "bundle exec quality_gate fast",
      "bundle exec quality_gate verify",
      "bundle exec quality_gate audit"
    ].freeze
    def test_settings_template_is_inert_and_documents_the_current_defaults
      with_rendered_template("quality_gate.yml.tt") do |content, destination_root|
        assert_nil YAML.safe_load(content)
        assert(content.lines.reject { _1.strip.empty? }.all? { _1.start_with?("#") })
        expected = Config.defaults.reject { |key, _value| key == :gates }
        assert_equal stringify_keys(expected), YAML.safe_load(uncomment(content))
        refute_includes content, destination_root
      end
    end

    def test_settings_template_explains_how_to_disable_coverage_budgets
      with_rendered_template("quality_gate.yml.tt") do |content|
        assert_includes content, "Leave the entire mapping commented to disable coverage budgeting."
      end
    end

    def test_rubocop_template_contains_only_the_host_inheritance_rule
      with_rendered_template("rubocop.yml.tt") do |content, destination_root|
        assert_equal "inherit_gem: { quality_gate: config/rubocop.yml }\n", content
        refute_includes content, destination_root
      end
    end

    def test_bullet_template_enables_only_test_and_development
      with_rendered_template("bullet.rb.tt") do |content, destination_root|
        assert_equal true, bullet_settings(content, destination_root, "test").fetch("enable")
        assert_equal true, bullet_settings(content, destination_root, "development").fetch("enable")
        assert_equal false, bullet_settings(content, destination_root, "production").fetch("enable")
      end
    end

    def test_bullet_template_requires_bullet_before_using_its_constant
      with_rendered_template("bullet.rb.tt") do |content|
        assert content.start_with?(<<~RUBY)
          # frozen_string_literal: true

          require 'bullet'

          Rails.application.config.after_initialize do
        RUBY
      end
    end

    def test_bullet_template_raises_only_in_test
      with_rendered_template("bullet.rb.tt") do |content, destination_root|
        assert_equal true, bullet_settings(content, destination_root, "test").fetch("raise")
        assert_equal false, bullet_settings(content, destination_root, "development").fetch("raise")
        assert_equal false, bullet_settings(content, destination_root, "production").fetch("raise")
      end
    end

    def test_bullet_template_logs_only_in_development
      with_rendered_template("bullet.rb.tt") do |content, destination_root|
        logging = %w[test development production].to_h do |environment|
          settings = bullet_settings(content, destination_root, environment)
          [environment, settings.values_at("bullet_logger", "rails_logger")]
        end

        assert_equal [false, false], logging.fetch("test")
        assert_equal [true, true], logging.fetch("development")
        assert_equal [false, false], logging.fetch("production")
      end
    end

    def test_bullet_template_uses_the_after_initialize_boundary_without_host_values
      with_rendered_template("bullet.rb.tt") do |content, destination_root|
        assert_includes content, "Rails.application.config.after_initialize do"
        refute_includes content, destination_root
      end
    end

    def test_strong_migrations_template_uses_the_newest_migration_version
      with_destination_root do |destination_root|
        write_migration(destination_root, "20250101000000_create_accounts.rb")
        write_migration(destination_root, "20260202000000_add_status_to_accounts.rb")

        content = render_template("strong_migrations.rb.tt", destination_root)

        assert_equal <<~RUBY, content
          # frozen_string_literal: true

          require 'strong_migrations'

          # Generated by Quality Gate.
          StrongMigrations.start_after = 20_260_202_000_000
        RUBY
      end
    end

    def test_strong_migrations_template_requires_strong_migrations_before_using_its_constant
      with_rendered_template("strong_migrations.rb.tt") do |content|
        assert content.start_with?(<<~RUBY)
          # frozen_string_literal: true

          require 'strong_migrations'

          # Generated by Quality Gate.
        RUBY
      end
    end

    def test_strong_migrations_template_normalizes_zero_padded_versions_to_valid_ruby
      with_destination_root do |destination_root|
        write_migration(destination_root, "007_create_accounts.rb")
        write_migration(destination_root, "008_add_index.rb")

        content = render_template("strong_migrations.rb.tt", destination_root)
        stdout, stderr, status = Open3.capture3(RbConfig.ruby, "-c", stdin_data: content)

        assert_predicate status, :success?, "#{stdout}#{stderr}"
        assert_equal <<~RUBY, content
          # frozen_string_literal: true

          require 'strong_migrations'

          # Generated by Quality Gate.
          StrongMigrations.start_after = 8
        RUBY
      end
    end

    def test_strong_migrations_template_handles_glob_metacharacters_in_the_destination_root
      with_destination_root do |parent|
        destination_root = File.join(parent, "host[quality]")
        write_migration(destination_root, "20260202000000_create_accounts.rb")

        content = render_template("strong_migrations.rb.tt", destination_root)

        assert_equal <<~RUBY, content
          # frozen_string_literal: true

          require 'strong_migrations'

          # Generated by Quality Gate.
          StrongMigrations.start_after = 20_260_202_000_000
        RUBY
      end
    end

    def test_strong_migrations_template_explains_an_absent_migration_directory
      with_rendered_template("strong_migrations.rb.tt") do |content|
        assert_equal <<~RUBY, content
          # frozen_string_literal: true

          require 'strong_migrations'

          # Generated by Quality Gate.
          # Set StrongMigrations.start_after after the first migration exists.
        RUBY
      end
    end

    def test_strong_migrations_template_explains_an_empty_migration_directory
      with_destination_root do |destination_root|
        FileUtils.mkdir_p(File.join(destination_root, "db/migrate"))

        content = render_template("strong_migrations.rb.tt", destination_root)

        assert_equal <<~RUBY, content
          # frozen_string_literal: true

          require 'strong_migrations'

          # Generated by Quality Gate.
          # Set StrongMigrations.start_after after the first migration exists.
        RUBY
      end
    end

    def test_strong_migrations_template_ignores_invalid_migration_filenames
      with_destination_root do |destination_root|
        write_migration(destination_root, "20250101000000_create_accounts.rb")
        write_migration(destination_root, "latest_add_status.rb")
        write_migration(destination_root, "99999999999999_not_a_migration.txt")

        content = render_template("strong_migrations.rb.tt", destination_root)

        assert_includes content, "StrongMigrations.start_after = 20_250_101_000_000"
        refute_includes content, "99999999999999"
      end
    end

    def test_generated_hooks_embed_the_shared_filesystem_source_and_remain_standalone
      shared_source = File.binread(File.join(InstallGenerator.source_root, "hook_log_filesystem.rb.tt"))

      %w[quality_gate_fast.rb.tt quality_gate_verify_stop.rb.tt].each do |name|
        with_rendered_template(name) do |content|
          assert_equal 1, content.scan(shared_source).length
          refute_includes content, "<%"
          refute_match(/^\s*require(?:_relative)? ["'].*quality_gate/, content)
          assert_predicate RubyVM::InstructionSequence.compile(content), :itself
        end
      end
    end

    def test_claude_settings_template_matches_the_supported_hook_schemas
      with_rendered_template("claude_settings.json.tt") do |content, destination_root|
        parsed = JSON.parse(content)
        hooks = parsed.fetch("hooks")

        assert_equal ["hooks"], parsed.keys
        assert_equal %w[PostToolUse Stop], hooks.keys
        assert_equal(
          [
            {
              "matcher" => "Edit|Write",
              "hooks" => [
                {
                  "type" => "command",
                  "command" => "${CLAUDE_PROJECT_DIR}/.claude/hooks/quality_gate_fast.rb",
                  "args" => [],
                  "timeout" => 30
                }
              ]
            }
          ],
          hooks.fetch("PostToolUse")
        )
        assert_equal(
          [
            {
              "hooks" => [
                {
                  "type" => "command",
                  "command" => "${CLAUDE_PROJECT_DIR}/.claude/hooks/quality_gate_verify_stop.rb",
                  "args" => [],
                  "timeout" => 300
                }
              ]
            }
          ],
          hooks.fetch("Stop")
        )
        refute hooks.fetch("Stop").first.key?("matcher")
        refute_includes content, destination_root
      end
    end
    # rubocop:enable Metrics/BlockLength

    def test_agents_section_template_contains_the_agent_contract_markers_commands_and_exit_codes
      with_rendered_template("agents_section.md.tt") do |content, destination_root|
        assert_includes content, "<!-- quality_gate agent contract — start -->"
        assert_includes content, "<!-- quality_gate agent contract — end -->"
        QUALITY_GATE_COMMANDS.each { assert_includes content, _1 }
        assert_match(/Claude Code hooks.*verify.*automatically.*session end/i, content)
        assert_match(/other clients.*Codex.*verify.*manually/i, content)
        assert_includes content, "Fix findings before you continue editing."
        assert_match(/exit 0.*clean/i, content)
        assert_match(/exit 1.*finding/i, content)
        assert_match(/exit 2.*tool failure/i, content)
        assert_match(/10-second/i, content)
        assert_match(/120-second/i, content)
        assert_match(/hook.*unavailable/i, content)
        assert_includes content, "bin/rails generate quality_gate:install --agents"
        refute_includes content, destination_root
      end
    end

    private

    def with_rendered_template(template_name)
      with_destination_root do |destination_root|
        yield render_template(template_name, destination_root), destination_root
      end
    end

    def with_destination_root(&)
      Dir.mktmpdir("quality-gate-generator", &)
    end

    def render_template(template_name, destination_root)
      source = File.join(InstallGenerator.source_root, template_name)
      assert File.file?(source), "expected generator template at #{source}"

      destination = File.join("rendered", template_name.delete_suffix(".tt"))
      generator = InstallGenerator.new([], {}, destination_root: destination_root)
      generator.template(template_name, destination, verbose: false)
      File.read(File.join(destination_root, destination))
    end

    def write_migration(destination_root, filename)
      directory = File.join(destination_root, "db/migrate")
      FileUtils.mkdir_p(directory)
      File.write(File.join(directory, filename), "# migration fixture\n")
    end

    def uncomment(content)
      content.lines.map { _1.sub(/\A# ?/, "") }.join
    end

    def stringify_keys(value)
      case value
      when Hash
        value.to_h { |key, child| [key.to_s, stringify_keys(child)] }
      when Array
        value.map { stringify_keys(_1) }
      else
        value
      end
    end

    def bullet_settings(content, destination_root, environment)
      path = File.join(destination_root, "rendered_bullet.rb")
      File.write(path, content)
      stdout, stderr, status = Open3.capture3(RbConfig.ruby, "-e", bullet_probe, path, environment)
      assert_predicate status, :success?, stderr

      JSON.parse(stdout)
    end

    def bullet_probe
      <<~'RUBY'
        require "json"
        require "bullet"

        Environment = Struct.new(:name) do
          def test? = name == "test"
          def development? = name == "development"
        end

        Config = Struct.new(:unused) do
          def after_initialize(&block) = block.call
        end

        Application = Struct.new(:config)

        module Rails
          class << self
            attr_accessor :application, :env
          end
        end

        module Bullet
          class << self
            attr_accessor :enable, :bullet_logger, :rails_logger
            attr_writer :raise

            def raise = @raise
          end
        end

        Rails.env = Environment.new(ARGV.fetch(1))
        Rails.application = Application.new(Config.new)
        load ARGV.fetch(0)

        puts JSON.generate(
          enable: Bullet.enable,
          raise: Bullet.raise,
          bullet_logger: Bullet.bullet_logger,
          rails_logger: Bullet.rails_logger
        )
      RUBY
    end
  end
end
